dictionaries = [
    "en_us",
    "en_gb",
    "ru",
]
words = [
    "agpl",
    "apiswitch",
    "asic",
    "btrom",
    "chipdata",
    "cointype",
    "dyn",
    "ecb",
    "eeprom",
    "fanspeed",
    "fastboot",
    "fwversion",
    "heatmode",
    "hwversion",
    "idk",
    "iin",
    "ledstatus",
    "oneshot",
    "pcbsn",
    "pkcs",
    "serde",
    "swversion",
    "tokio",
    "upfreq",
    "vin",
    "vout",
    "waru",
    "whatsminer",
    "zeroize",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
]
